In [13]:
import numpy as np
import sympy as sym
import math as math
import matplotlib.pyplot as plt

x = sym.Symbol('x',real=True)
y = sym.Symbol('y',real=True)

def Function(T, Tam_Banda,x):
    return (np.tanh(np.sqrt(x**2+Tam_Banda**2)*300/2*T))/np.sqrt(x**2+Tam_Banda**2)

n=50



In [14]:
def GetLegendre(n,x,y):
    
    y = (x**2 - 1)**n
    
    poly = sym.diff( y,x,n )/(2**n*np.math.factorial(n))
    
    return poly

In [15]:
Legendre = []
DLegendre = []

for i in range(n+1):
    Poly = GetLegendre(i,x,y)
    Legendre.append(Poly)
    DLegendre.append(sym.diff(Poly,x,1))

C:\Users\simon\AppData\Local\Temp\ipykernel_196\3349966814.py:5: DeprecationWarning: `np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`
  poly = sym.diff( y,x,n )/(2**n*np.math.factorial(n))


In [16]:
def GetNewton(f,df,xn,itmax=10000,precision=1e-14):
    
    error = 1.
    it = 0
    
    while error >= precision and it < itmax:
        
        try:
            
            xn1 = xn - f(xn)/df(xn)
            
            error = np.abs(f(xn)/df(xn))
            
        except ZeroDivisionError:
            print('Zero Division')
            
        xn = xn1
        it += 1
        
    if it == itmax:
        return False
    else:
        return xn

In [17]:
def GetRoots(f,df,x,tolerancia = 10):
    
    Roots = np.array([])
    
    for i in x:
        
        root = GetNewton(f,df,i)
        
        if root != False:
            
            croot = np.round( root, tolerancia )
            
            if croot not in Roots:
                Roots = np.append(Roots, croot)
                
    Roots.sort()
    
    return Roots

In [18]:
def GetAllRoots(n,xn,Legendre,DLegendre):
    
    poly = sym.lambdify([x],Legendre[n],'numpy')
    Dpoly = sym.lambdify([x],DLegendre[n],'numpy')
    Roots = GetRoots(poly,Dpoly,xn)
    
    return Roots

In [19]:

xn = np.linspace(-1,1,100)
Roots1 = GetAllRoots(n,xn,Legendre,DLegendre)
Roots1

array([-0.9988664 , -0.95661096, -0.93665662, -0.91307856, -0.88596798,
       -0.85542977, -0.82158207, -0.60770293, -0.5571583 , -0.50445814,
       -0.44980634, -0.39341431, -0.33550025, -0.27628819, -0.21600724,
       -0.15489059, -0.0931747 , -0.03109834,  0.03109834,  0.0931747 ,
        0.15489059,  0.21600724,  0.27628819,  0.33550025,  0.39341431,
        0.44980634,  0.50445814,  0.5571583 ,  0.65589647,  0.70155247,
        0.7444943 ,  0.82158207,  0.85542977,  0.88596798,  0.91307856,
        0.93665662,  0.95661096,  0.9988664 ])

In [20]:
def GetWeights(Roots,DLegendre):
    
    Dpoly = sym.lambdify([x],DLegendre[n],'numpy')
    Weights = 2/((1-Roots**2)*Dpoly(Roots)**2)
    
    return Weights


In [21]:
Pesos=GetWeights(Roots1,DLegendre)
Pesos

array([0.00290862, 0.01811556, 0.02178024, 0.02536067, 0.02884299,
       0.03221373, 0.03545984, 0.04940094, 0.0516557 , 0.05371062,
       0.05555774, 0.05718993, 0.05860085, 0.05978506, 0.06073797,
       0.0614559 , 0.06193607, 0.06217662, 0.06217662, 0.06193607,
       0.0614559 , 0.06073797, 0.05978506, 0.05860085, 0.05718993,
       0.05555774, 0.05371062, 0.0516557 , 0.04695505, 0.0443275 ,
       0.04152846, 0.03545984, 0.03221373, 0.02884299, 0.02536067,
       0.02178024, 0.01811556, 0.00290862])

In [38]:

dT=np.linspace(1,20,190001)

f= lambda x: x**2
len(Pesos)
dT

array([ 1.    ,  1.0001,  1.0002, ..., 19.9998, 19.9999, 20.    ])

In [26]:
def IntegralLegendre(f,n):
    Roots,Weights=np.polynomial.legendre.leggauss(n)
    return np.sum(Weights*f(Roots))




In [49]:

for T in dT:
    function=lambda x: (np.tanh(np.sqrt(x**2+0.0001**2)*300/(2*T)))/np.sqrt(x**2+0.0001**2)
    I=IntegralLegendre(function,10)
    if np.abs(I-1/0.3) <0.01 :
        Tc=T
Tc
        

    


0

In [42]:
Tc

0

In [ ]:
def Integral_a_b(f,a,b,n):
    sum=0
    for k in range (n):
        Raices=GetAllRoots(n,xn, Legendre, DLegendre)
        Pesos=GetWeights(Raices,DLegendre)
        ev=(Raices[k]*(b-a)+b+a)/2
        sum+= Pesos[k]*f(ev)
    multiplicador=(b-a)/2
    salida=multiplicador*sum
    return salida
ress=Integral_a_b(f,3,5,50)
ress

32.666666663454