In [155]:
import numpy as np
import sympy as sym
import math as math
import matplotlib.pyplot as plt

x = sym.Symbol('x',real=True)
y = sym.Symbol('y',real=True)

In [156]:
#Método para encontrar la integral numerador: Cuadratura Gauss-Legendre
#Método para encontrar la integral denominador : Cuadratura Gauss-Laguerre

In [157]:
Roots,Weights=np.polynomial.legendre.leggauss(20)

In [158]:
Roots

array([-0.9931286 , -0.96397193, -0.91223443, -0.83911697, -0.74633191,
       -0.63605368, -0.510867  , -0.37370609, -0.22778585, -0.07652652,
        0.07652652,  0.22778585,  0.37370609,  0.510867  ,  0.63605368,
        0.74633191,  0.83911697,  0.91223443,  0.96397193,  0.9931286 ])

In [159]:
Weights

array([0.01761401, 0.04060143, 0.06267205, 0.08327674, 0.10193012,
       0.11819453, 0.13168864, 0.14209611, 0.14917299, 0.15275339,
       0.15275339, 0.14917299, 0.14209611, 0.13168864, 0.11819453,
       0.10193012, 0.08327674, 0.06267205, 0.04060143, 0.01761401])

In [160]:
b=(((3*10**8)/(100*10**-9))*6.626*10**-34)/((1.3806*10**-23)*(5772))
b

24.944712037280482

In [161]:
a=(((3*10**8)/(400*10**-9))*6.626*10**-34)/((1.3806*10**-23)*(5772))
a

6.2361780093201205

In [162]:
f1= lambda x: x**3/((np.e**x)-1)

In [163]:
def Integral_a_b(f,a,b,n):
    sum=0
    for k in range (n):
        Raices=Roots
        Pesos=Weights
        ev=(Raices[k]*(b-a)+b+a)/2
        sum+= Pesos[k]*f(ev)
    multiplicador=(b-a)/2
    salida=multiplicador*sum
    return salida

In [164]:
Integral_a_b(f1,a,b,20)


0.7886360406075117

In [165]:
RootsH,WeightsH=np.polynomial.hermite.hermgauss(20)

In [166]:
f= lambda x: x**3/(1-(1/np.exp(x)))
def Laguerre(n):
    Roots,Weights=np.polynomial.laguerre.laggauss(n)
    suma= np.sum(Weights*f(Roots))
    return suma

Laguerre(20)



6.493939402219589

In [167]:
Resultado=0.7886360406075117/6.493939402219589
Resultado

0.12144185397510186

In [168]:
#Podemos ver que efectivamente el resultado es más o menos 12%

La diferencia entre el porcentaje calculado y el porcentaje que se recibe en Bogotá se debe a que la capa de ozono dispersa en su totalidadad la ondas tipo C (cortas), que tienen longitud de onda entre 280-100 y parcialmente las tipo B de longitud 315-280 (ondas medias) por lo que un minimo porcentaje de esas ondas llegan a la tierra. No es el caso de las ondas tipo A  de longitud de onda 400-315(largas) de las que proviene principalmente la radiación. ultravioleta.


In [169]:
def GetLaguerreRecursive(n,x):

    if n==0:
        poly = sym.Number(1)
    elif n==1:
        poly = 1-x
    else:
        poly = ((2*(n-1)+1-x)*GetLaguerreRecursive(n-1,x)-(n-1)*GetLaguerreRecursive(n-2,x))/n
   
    return sym.expand(poly, x)


In [170]:
GetLaguerreRecursive(2,x)

x**2/2 - 2*x + 1

In [171]:
def GetLaguerreRecursive(n,x):

    if n==0:
        poly = sym.Number(1)
    elif n==1:
        poly = 1-x
    else:
        poly = ((2*(n-1)+1-x)*GetLaguerreRecursive(n-1,x)-(n-1)*GetLaguerreRecursive(n-2,x))/n
   
    return sym.expand(poly, x)




def GetDLaguerre(n,x):
    Pn = GetLaguerreRecursive(n,x)
    return sym.diff(Pn,x,1)

def GetNewton(f,df,xn,itmax=10000,precision=1e-14):
    
    error = 1.
    it = 0
    
    while error >= precision and it < itmax:
        
        try:
            
            xn1 = xn - f(xn)/df(xn)
            
            error = np.abs(f(xn)/df(xn))
            
        except ZeroDivisionError:
            print('Zero Division')
            
        xn = xn1
        it += 1
        
    if it == itmax:
        return False
    else:
        return xn
    

def GetRoots(f,df,x,tolerancia = 10):
    
    Roots = np.array([])
    
    for i in x:
        
        root = GetNewton(f,df,i)

        if  type(root)!=bool:
            croot = np.round( root, tolerancia )
            
            if croot not in Roots:
                Roots = np.append(Roots, croot)
                
    Roots.sort()
    
    return Roots

def GetAllRootsGLag(n):
    N=n+(n-1)*n**(1/2)

    xn = np.linspace(0,N,300)
    
    Laguerre = []
    DLaguerre = []
    
    for i in range(n+1):
        Laguerre.append(GetLaguerreRecursive(i,x))
        DLaguerre.append(GetDLaguerre(i,x))
    
    poly = sym.lambdify([x],Laguerre[n],'numpy')
    Dpoly = sym.lambdify([x],DLaguerre[n],'numpy')
    Roots = GetRoots(poly,Dpoly,xn)

    if len(Roots) != n:
        ValueError('El número de raíces debe ser igual al n del polinomio.')
    
    return Roots






In [172]:
RaicesGLag=GetAllRootsGLag(2)
RaicesGLag

array([0.58578644, 3.41421356])

In [173]:
f2= lambda x: (x-3.41421356)/(0.58578644-3.41421356)
def Laguerre(n):
    Roots,Weights=np.polynomial.laguerre.laggauss(n)
    suma= np.sum(Weights*f2(Roots))
    return suma

Peso1=Laguerre(20)
Peso1

0.8535533911865556

In [174]:
f3= lambda x: (x-0.58578644)/(3.41421356-0.58578644)
def Laguerre(n):
    Roots,Weights=np.polynomial.laguerre.laggauss(n)
    suma= np.sum(Weights*f3(Roots))
    return suma

Peso2=Laguerre(20)
Peso2

0.14644660881344462

In [175]:
funcion= lambda x: x**3
suma=Peso1*funcion(RaicesGLag[0])+Peso2*funcion(RaicesGLag[1])
suma

5.999999976621394

In [177]:
error=np.abs(((5.999999976621394-6)/6)*100)
error

3.896434286332351e-07

In [ ]:
#Como podemos ver, se puede comprobar que se encuentra el resultado con error de 3.896434286332351e-07