In [11]:
import numpy as np
import sympy as sym

In [12]:
A=np.array([[4, -2, 1], [20, -7, 12], [-8, 13, 17]])
A

array([[ 4, -2,  1],
       [20, -7, 12],
       [-8, 13, 17]])

In [13]:
def descomposicionLU(A):
  filas_A, columnas_A = A.shape
  n=columnas_A
  L=np.zeros((n,n))
  U=np.zeros((n,n))
  U[0,:]=A[0,:]
  for i in range(n):
    L[i,i]=1
  L[1,0]=A[1,0]/U[0,0]
  U[1,1]=A[1,1]-(U[0,1]*L[1,0])
  U[1,2]=A[1,2]-(L[1,0]*U[0,2])
  L[2,0]=A[2,0]/U[0,0]
  L[2,1]=(A[2,1]-(U[0,1]*L[2,0]))/U[1,1]
  U[2,2]=A[2,2]-(U[0,2]*L[2,0])-(U[1,2]*L[2,1])
  return L,U


In [14]:
A_descompuesta= descomposicionLU(A)
A_descompuesta

(array([[ 1.,  0.,  0.],
        [ 5.,  1.,  0.],
        [-2.,  3.,  1.]]),
 array([[ 4., -2.,  1.],
        [ 0.,  3.,  7.],
        [ 0.,  0., -2.]]))