In [30]:
import numpy as np
import sympy as sym
x = sym.Symbol('x',real=True)
y = sym.Symbol('y',real=True)
k=0.0732

In [31]:
def f(x,y):
    
    z = x + sym.I*y
    f = sym.sin(z)**6+(sym.sin(z)**2)*k-k
    f = f.expand()
    return sym.re(f),sym.im(f)

In [32]:
f0,f1 = f(x,y)
F = [f0,f1]
F

[sin(x)**6*cosh(y)**6 - 15*sin(x)**4*cos(x)**2*sinh(y)**2*cosh(y)**4 + 15*sin(x)**2*cos(x)**4*sinh(y)**4*cosh(y)**2 + 0.0732*sin(x)**2*cosh(y)**2 - cos(x)**6*sinh(y)**6 - 0.0732*cos(x)**2*sinh(y)**2 - 0.0732,
 6*sin(x)**5*cos(x)*sinh(y)*cosh(y)**5 - 20*sin(x)**3*cos(x)**3*sinh(y)**3*cosh(y)**3 + 6*sin(x)*cos(x)**5*sinh(y)**5*cosh(y) + 0.1464*sin(x)*cos(x)*sinh(y)*cosh(y)]

In [33]:
J = sym.zeros(2,2)

for i in range(2):
    for j in range(2):
        if j==0:
            J[i,j] = sym.diff(F[i],x,1)
        else:
            J[i,j] = sym.diff(F[i],y,1)

J

Matrix([
[     30*sin(x)**5*cos(x)*sinh(y)**2*cosh(y)**4 + 6*sin(x)**5*cos(x)*cosh(y)**6 - 60*sin(x)**3*cos(x)**3*sinh(y)**4*cosh(y)**2 - 60*sin(x)**3*cos(x)**3*sinh(y)**2*cosh(y)**4 + 6*sin(x)*cos(x)**5*sinh(y)**6 + 30*sin(x)*cos(x)**5*sinh(y)**4*cosh(y)**2 + 0.1464*sin(x)*cos(x)*sinh(y)**2 + 0.1464*sin(x)*cos(x)*cosh(y)**2, 6*sin(x)**6*sinh(y)*cosh(y)**5 - 60*sin(x)**4*cos(x)**2*sinh(y)**3*cosh(y)**3 - 30*sin(x)**4*cos(x)**2*sinh(y)*cosh(y)**5 + 30*sin(x)**2*cos(x)**4*sinh(y)**5*cosh(y) + 60*sin(x)**2*cos(x)**4*sinh(y)**3*cosh(y)**3 + 0.1464*sin(x)**2*sinh(y)*cosh(y) - 6*cos(x)**6*sinh(y)**5*cosh(y) - 0.1464*cos(x)**2*sinh(y)*cosh(y)],
[-6*sin(x)**6*sinh(y)*cosh(y)**5 + 60*sin(x)**4*cos(x)**2*sinh(y)**3*cosh(y)**3 + 30*sin(x)**4*cos(x)**2*sinh(y)*cosh(y)**5 - 30*sin(x)**2*cos(x)**4*sinh(y)**5*cosh(y) - 60*sin(x)**2*cos(x)**4*sinh(y)**3*cosh(y)**3 - 0.1464*sin(x)**2*sinh(y)*cosh(y) + 6*cos(x)**6*sinh(y)**5*cosh(y) + 0.1464*cos(x)**2*sinh(y)*cosh(y),     30*sin(x)**5*cos(x)*sinh(y)**2*

In [34]:
InvJ = J.inv(method='LU')
InvJ

Matrix([
[((-6*sin(x)**6*sinh(y)*cosh(y)**5 + 60*sin(x)**4*cos(x)**2*sinh(y)**3*cosh(y)**3 + 30*sin(x)**4*cos(x)**2*sinh(y)*cosh(y)**5 - 30*sin(x)**2*cos(x)**4*sinh(y)**5*cosh(y) - 60*sin(x)**2*cos(x)**4*sinh(y)**3*cosh(y)**3 - 0.1464*sin(x)**2*sinh(y)*cosh(y) + 6*cos(x)**6*sinh(y)**5*cosh(y) + 0.1464*cos(x)**2*sinh(y)*cosh(y))*(6*sin(x)**6*sinh(y)*cosh(y)**5 - 60*sin(x)**4*cos(x)**2*sinh(y)**3*cosh(y)**3 - 30*sin(x)**4*cos(x)**2*sinh(y)*cosh(y)**5 + 30*sin(x)**2*cos(x)**4*sinh(y)**5*cosh(y) + 60*sin(x)**2*cos(x)**4*sinh(y)**3*cosh(y)**3 + 0.1464*sin(x)**2*sinh(y)*cosh(y) - 6*cos(x)**6*sinh(y)**5*cosh(y) - 0.1464*cos(x)**2*sinh(y)*cosh(y))/((30*sin(x)**5*cos(x)*sinh(y)**2*cosh(y)**4 + 6*sin(x)**5*cos(x)*cosh(y)**6 - 60*sin(x)**3*cos(x)**3*sinh(y)**4*cosh(y)**2 - 60*sin(x)**3*cos(x)**3*sinh(y)**2*cosh(y)**4 + 6*sin(x)*cos(x)**5*sinh(y)**6 + 30*sin(x)*cos(x)**5*sinh(y)**4*cosh(y)**2 + 0.1464*sin(x)*cos(x)*sinh(y)**2 + 0.1464*sin(x)*cos(x)*cosh(y)**2)*(-(-6*sin(x)**6*sinh(y)*cosh(y)**5 + 

In [35]:
Fn = sym.lambdify([x,y],F,'numpy')
IJn = sym.lambdify([x,y],InvJ,'numpy')

In [36]:
IJn(1.,1.)

array([[ 0.00350961,  0.02014947],
       [-0.02014947,  0.00350961]])

In [37]:
def NewtonRaphson(z,Fn,Jn,itmax=100,precision=1e-9):
    
    error = 1
    it = 0
    
    while error > precision and it < itmax:
        
        IFn = Fn(z[0],z[1])
        IJn = Jn(z[0],z[1])
        
        z1 = z - np.dot(IJn,IFn)
        
        error = np.max( np.abs(z1-z) )
        
        z = z1
        it +=1
        
    print(it)
    return z

In [39]:
z0 = np.array([1,0])
zsol0 = NewtonRaphson(z0,Fn,IJn)
zsol0

6


array([0.64393353, 0.        ])

In [40]:
z1=np.array([1,2])
zsol1= NewtonRaphson(z1, Fn, IJn)
zsol1

22


array([ 0.32196677, -0.56200476])

In [41]:
z2=np.array([5,0])
zsol2= NewtonRaphson(z2, Fn, IJn)
zsol2

6


array([5.63925177, 0.        ])

In [44]:
z3=np.array([3,2])
zsol3= NewtonRaphson(z3, Fn, IJn)
zsol3

19


array([2.81962589, 0.56200476])